CREATE SCHEMA IF NOT EXISTS cocktailbar;

CREATE TYPE ingredient_type AS ENUM ('cola', 'baccardi_spiced');

CREATE TABLE cocktailbar.available_ingredients (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);